### PR TITLE
Validate

### PR DESCRIPTION
**Pull request by dkhamsing**
Status: do not merge :bomb: :warning: 

Hey @marcelvoss this is a work in progress but it would be applied to the whole model for safe access (and the other models too)

What do you think?

### CODE REVIEW

**Comment by marcelvoss** [comment]
Hm, I have a different idea but I'll compare them and check which one fits better into the concept. :smile:

**Comment by dkhamsing** [comment]
Cool

**Comment by marcelvoss** [comment]
Fixed this with 4f3a3a2.

**Comment by dkhamsing** [comment]
nice

**Pull request closed without merging**
